import React, {useState, useEffect} from 'react'
import {useRouter} from 'next/router'
import Axios from 'axios'
import {url} from '../utils/constants'
import Head from 'next/head'
import NavLink from 'next/link'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import DeleteForeverIcon from '@material-ui/icons/DeleteForever';
import EditIcon from '@material-ui/icons/Edit';
import CircularProgress from '@material-ui/core/CircularProgress';
import { Icon } from '@material-ui/core';

export default function Home() {
  const [data, setData] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(false)
  const [reload, setReload] = useState(false)
   const router = useRouter()

  const fetchPosts = async(url)=>{
    setLoading(true)
    const response = await Axios.get(url)
    const {data : {Posts}} = response
    setData(Posts)
    setLoading(false)
  }

  const deletePost = async(id)=>{
        const postid = id
       
             if(window.confirm('Delete this post?')){
              await Axios.delete('https://blog-api-live.herokuapp.com/'+ postid)
              .then(result =>{
                  router.replace("/");
                  setReload(prev =>{
                    return !prev
                  })
            })
            .catch(error=>{
                setError(true)
                alert(error)
                setTimeout(() => {
                    setError(false)
                }, 5000);
            })
        }
    }
    const editPost = async(postid)=>{
  //  const updateArray = [{"propertyName": "title" , "propertyValue": "A Meeting bag"}]

    router.push(`/update/${postid}`)

          // await Axios.patch('https://blog-api-live.herokuapp.com/60b64af0fc8aa300046c43ca' ,{ "title" : "A Meeting bag"})
          //   .then(result =>{
          //       router.replace("/");
          //       setReload(prev =>{
          //         return !prev
          //       })
          //   })
          //   .catch(error=>{
          //       setError(true)
          //       alert(error)
          //       setTimeout(() => {
          //           setError(false)
          //       }, 5000);
          //   })

    }

  useEffect(() => {
    fetchPosts(url)
  }, [reload])


  return (
    <div className={styles.container}>
      <Head>
        <title>Smart's Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
        <meta
        name="viewport"
        content="minimum-scale=1, initial-scale=1, width=device-width"
      />
      </Head>

      
      
      <div className={styles.belowNav} >
          {/* <span>WELCOME TO SMART'S <span>JavaScript</span> BLOG</span> */}
       <span><NavLink href='./add-post'> Add Post</NavLink></span>
    </div>
    <main className='page' >
      
{  loading ?
<div 
style={{display: 'grid', placeItems: 'center', width: '100%', height:'100%'}}
><CircularProgress /></div>
:
<div>
      {data.map(post =>{
        const {_id, title, postbody} = post
        
        return (<div className='post'>
        <Link href={`/${_id}`} >
        <div key={_id} className=''>
        <h4>{title}</h4>
        <p>{postbody}</p>
        
        </div>
         </Link>
         <div style={{display: 'flex', float: 'right'}}>
         <button onClick={()=>editPost(_id)}>EDIT</button>
        <button onClick={()=>deletePost(_id)}>DELETE</button>
         </div>
         </div>)
      })}
  </div>
  }
      
      </main>
    </div>
  )
}

