import React, {useState, useEffect} from 'react'
import {useRouter} from 'next/router'
import Axios from 'axios'
import {url} from '../utils/constants'
import Head from 'next/head'
import NavLink from 'next/link'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import DeleteForeverIcon from '@material-ui/icons/DeleteForever';
import EditIcon from '@material-ui/icons/Edit';
import CircularProgress from '@material-ui/core/CircularProgress';
import { Icon } from '@material-ui/core';
import {FaTrash, FaEdit} from "react-icons/fa"

export default function Home() {
  const [data, setData] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(false)
  const [reload, setReload] = useState(false)
   const router = useRouter()

  const fetchPosts = async(url)=>{
    setLoading(true)
    const response = await Axios.get(url)
    const {data : {Posts}} = response
    setData(Posts)
    setLoading(false)
  }

  const deletePost = async(id)=>{
        const postid = id
       
             if(window.confirm('Delete this post?')){
              await Axios.delete('https://blog-api-live.herokuapp.com/'+ postid)
              .then(result =>{
                  router.replace("/");
                  setReload(prev =>{
                    return !prev
                  })
            })
            .catch(error=>{
                setError(true)
                alert(error)
                setTimeout(() => {
                    setError(false)
                }, 5000);
            })
        }
    }
    const editPost = async(postid)=>{
  //  const updateArray = [{"propertyName": "title" , "propertyValue": "A Meeting bag"}]

    router.push(`/update/${postid}`)
    }

  useEffect(() => {
    fetchPosts(url)
  }, [reload])


  return (
    <div className={styles.container}>
      <Head>
        <title>Smart's Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
        <meta
        name="viewport"
        content="minimum-scale=1, initial-scale=1, width=device-width"
      />
      </Head>

      

      <div className={styles.belowNav} >
          {/* <span>WELCOME TO SMART'S <span>JavaScript</span> BLOG</span> */}
       <span><NavLink href='./add-post'> Add Post</NavLink></span>
    </div>
    <main className='page' >
      
{  loading ?
<div className='spinner'><CircularProgress /></div>
:
<div>
      {data.reverse().map(post =>{
        const {_id, title, postbody} = post
        
        return (<div className='post'>
        <Link href={`/${_id}`} >
        <div key={_id} className=''>
       <h3>{title}</h3>
        <p className={styles.postbody}>{postbody}</p>
        
        </div>
         </Link>
         <div className={styles.btnContainer}>
         <button className={styles.buttonEdit} onClick={()=>editPost(_id)}><FaEdit className={styles.edit} /></button>
        <button className={styles.buttonDelete} onClick={()=>deletePost(_id)}><FaTrash className={styles.delete} /></button>
         </div>
         </div>)
      })}
  </div>
  }
      
      </main>
    </div>
  )
}

